wandb_version: 1

Device:
  desc: null
  value:
    CPU_NUM: 16
    TASK_PER_IND: 1
ENV:
  desc: null
  value:
    NAME: scene_dbAlpha_test
    HEADLESS: true
ES_params:
  desc: null
  value:
    POPSIZE: 500
    EPISODE_LENGTH: 200
    REWARD_FUNC: abs_y_distance
    rank_fitness: true
    antithetic: true
    learning_rate: 0.01
    learning_rate_decay: 0.9999
    sigma_init: 0.1
    sigma_decay: 0.999
    learning_rate_limit: 0.001
    sigma_limit: 0.01
Train_params:
  desc: null
  value:
    EPOCH: 501
    EVAL_EVERY: 2
    SAVE_EVERY: 50
    USE_TRAIN_WEIGHT: true
Model:
  desc: null
  value:
    FEEDFORWARD:
      input:
        J_pos: 18
      output:
        J_pos: 18
      ARCHITECTURE:
        name: FeedForward
        size:
        - 18
        - 64
        - 32
        - 18
    HEBB:
      input:
        J_pos: 18
      output:
        J_pos: 18
      ARCHITECTURE:
        name: hebb
        size:
        - 18
        - 64
        - 32
        - 18
Wandb_log:
  desc: null
  value:
    use_WanDB: true
    project_name: dbAlpha_wandb_log
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683798950.362889
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.15.2
      8:
      - 5
