# config file for parameters of dbAlpha_hebb

# CPU
Device:
  CPU_NUM:  2 # workstation (32 failed), DELL 8
  TASK_PER_IND: 1
  
# Simulation Environments
ENV:
  NAME: 'scene_dbAlpha_test'
  HEADLESS: False # workstation (False), DELL (True)

# ES algorithm
ES_params:
  POPSIZE: 2 # workstation (500)
  EPISODE_LENGTH: 200 # workstation (200)
  REWARD_FUNC: 'abs_y_distance'
  rank_fitness: True
  antithetic: True
  learning_rate: 0.01
  learning_rate_decay: 0.9999
  sigma_init: 0.1
  sigma_decay: 0.999
  learning_rate_limit: 0.001
  sigma_limit: 0.01

# Training Params
Train_params:
  EPOCH: 1 # workstation (501)
  EVAL_EVERY: 2
  SAVE_EVERY: 100 # workstation (50)
  USE_TRAIN_WEIGHT: True

# Model
Model:
  FEEDFORWARD:
    input: 
      J_pos: 18
    output: 
      J_pos: 18
    ARCHITECTURE: 
      name: 'FeedForward' # 'FeedForward'
      size: [18, 64, 32, 18]
  HEBB:
    input: 
      J_pos: 18
    output: 
      J_pos: 18
    ARCHITECTURE: 
      name: 'hebb' # 'FeedForward'
      size: [18, 64, 32, 18]


# WanDB Data Logging
Wandb_log:
  use_WanDB: False # workstation (True)
  project_name: 'dbAlpha_wandb_log'