wandb_version: 1

Device:
  desc: null
  value:
    CPU_NUM: 12
    TASK_PER_IND: 1
ENV:
  desc: null
  value:
    NAME: scene_dbAlpha_test
    HEADLESS: true
ES_params:
  desc: null
  value:
    POPSIZE: 500
    EPISODE_LENGTH: 200
    REWARD_FUNC:
      NAME: abs_x_D_Pen_Orient
      ORIENTATION_WEIGHT: 1.0
      DISTANCE_WEIGHT: 2.0
    rank_fitness: true
    antithetic: true
    learning_rate: 0.1
    learning_rate_decay: 0.9999
    sigma_init: 1
    sigma_decay: 0.999
    learning_rate_limit: 0.001
    sigma_limit: 0.01
Train_params:
  desc: null
  value:
    EPOCH: 501
    EVAL_EVERY: 2
    SAVE_EVERY: 100
    USE_TRAIN_WEIGHT: false
Model:
  desc: null
  value:
    FEEDFORWARD:
      input:
        J_pos: 18
        J_torq: 18
        Orient: 3
      output:
        J_pos: 18
      ARCHITECTURE:
        name: FeedForward
        size:
        - 39
        - 128
        - 64
        - 18
    HEBB:
      input:
        J_pos: 18
        J_torq: 18
        Orient: 3
      output:
        J_pos: 18
      ARCHITECTURE:
        name: hebb
        size:
        - 39
        - 128
        - 64
        - 18
Wandb_log:
  desc: null
  value:
    use_WanDB: true
    project_name: dbAlpha_wandb_log
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684857591.604844
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.15.2
      8:
      - 5
